def second_info():
    print("This is a second info !")

    #simple example of exception

# class Ab:

#     def fun(self,x):
#             try:
#                 print(x/0)
    
#             except ZeroDivisionError as er:
#                 print("your exception is :",er)
# a=Ab()
# a.fun(10)


a=iter([1,2,3,4])
print(next(a))


     